language: node_js
node_js:
  - "lts/*"
branches:
  # This script will be run on the following branches only
  only:
    - master
    - staging
install:
  - npm install
after_success:
  # Zip deployment files with commit and timestamp
  - export ELASTICBEANSTALK_DEPLOYMENT_ZIP_FILE=$TRAVIS_COMMIT_$(date +%Y_%m_%d_%H_%M_%S).zip
  - zip -rq $ELASTICBEANSTALK_DEPLOYMENT_ZIP_FILE * -x .env-example .gitignore package-lock.json
deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID_FOR_DEPLOYMENT
    secret_access_key: $AWS_SECRET_ACCESS_KEY_FOR_DEPLOYMENT
    region: "ap-southeast-1"
    skip_cleanup: true
    zip_file: $ELASTICBEANSTALK_DEPLOYMENT_ZIP_FILE
    app: "isomer-cms"
    env: "isomercms-backend-prod"
    bucket_name: "isomercms-backend-prod"
    on:
      branch: master
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID_FOR_DEPLOYMENT
    secret_access_key: $AWS_SECRET_ACCESS_KEY_FOR_DEPLOYMENT
    region: "ap-southeast-1"
    skip_cleanup: true
    zip_file: $ELASTICBEANSTALK_DEPLOYMENT_ZIP_FILE
    app: "isomer-cms"
    env: "isomercms-backend-staging"
    bucket_name: "isomercms-backend-staging"
    on:
      branch: staging
