version: "3"
services:
  postgres:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_USER: isomer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: isomercms_dev
    ports:
      - "15432:5432"
    volumes:
      - isomercms_data:/var/lib/postgresql/data

volumes:
  isomercms_data:
