name: Deploy to staging

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/aws_deploy.yml
    with:
      aws-region: "ap-southeast-1"
      cicd-role: "arn:aws:iam::646878943557:role/redirection-github-oidc-role"
      ecr-repository: "isomer-infra-ecr"
      ecs-cluster-name: "redirection"
      ecs-web-service-name: "redir-web-ecs-service"
      ecs-container-name: "app-server"
      environment: "staging"
      shortEnv: "stg"
      task-definition-path: ".aws/deploy/backend-task-definition.staging.json"
    secrets: 
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      EFS_FILE_SYSTEM_ID: ${{ secrets.STAGING_EFS_FILE_SYSTEM_ID }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
